#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosAcceso
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PABLO")]
	public partial class DBloginDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBloginDataContext() : 
				base(global::DatosAcceso.Properties.Settings.Default.PABLOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBloginDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBloginDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBloginDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBloginDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIO")]
	public partial class TBL_USUARIO
	{
		
		private int _ID_USU;
		
		private string _USU_NOMBRE;
		
		private string _USU_EMAIL;
		
		private string _USU_PASSWORD;
		
		private string _USU_STATUS;
		
		public TBL_USUARIO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USU", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_USU
		{
			get
			{
				return this._ID_USU;
			}
			set
			{
				if ((this._ID_USU != value))
				{
					this._ID_USU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_NOMBRE", DbType="VarChar(50)")]
		public string USU_NOMBRE
		{
			get
			{
				return this._USU_NOMBRE;
			}
			set
			{
				if ((this._USU_NOMBRE != value))
				{
					this._USU_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_EMAIL", DbType="NChar(50)")]
		public string USU_EMAIL
		{
			get
			{
				return this._USU_EMAIL;
			}
			set
			{
				if ((this._USU_EMAIL != value))
				{
					this._USU_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_PASSWORD", DbType="NChar(170)")]
		public string USU_PASSWORD
		{
			get
			{
				return this._USU_PASSWORD;
			}
			set
			{
				if ((this._USU_PASSWORD != value))
				{
					this._USU_PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_STATUS", DbType="NChar(10)")]
		public string USU_STATUS
		{
			get
			{
				return this._USU_STATUS;
			}
			set
			{
				if ((this._USU_STATUS != value))
				{
					this._USU_STATUS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
